name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: ./Frontend

      # Step 4: Build the Vue.js app
      - name: Build
        run: npm run build
        working-directory: ./Frontend

      # Step 5: Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }} # Use PAT instead of GITHUB_TOKEN
          publish_dir: ./Frontend/dist
          publish_branch: gh-pages
          force_orphan: true # Ensures a clean deployment
